# Notes:
#
# Note: semantic-release depends on the GitHub liveryvideo "web" context for GH_TOKEN and NPM_TOKEN
# environment variables for repo write and package publish access.

version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:20.11.0

commands:
  npm_install:
    steps:
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ -d node_modules ]; then
              echo "Dependencies restored from cache already"
            else
              npm ci
            fi
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

jobs:
  semantic_release:
    executor: default
    steps:
      - checkout
      - npm_install
      # Disable husky git hooks to prevent commitlint from tripping on the generated changelog commit message
      - run: HUSKY=0 npx semantic-release

workflows:
  release:
    jobs:
      - semantic_release:
          context: web
          filters:
            branches:
              only: [main]
